apiVersion: v1
kind: ServiceAccount
metadata:
  name: aibrix-gpu-optimizer-sa
  namespace: aibrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-optimizer-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aibrix-gpu-optimizer-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: aibrix-gpu-optimizer-sa
    namespace: aibrix-system
roleRef:
  kind: ClusterRole
  name: gpu-optimizer-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibrix-gpu-optimizer
  namespace: aibrix-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibrix-gpu-optimizer
  template:
    metadata:
      labels:
        app: aibrix-gpu-optimizer
    spec:
      serviceAccountName: aibrix-gpu-optimizer-sa
      automountServiceAccountToken: true # Important!
      containers:
      - name: aibrix-gpu-optimizer
        image: aibrix/runtime:nightly
        command: ["python", "-m", "aibrix.gpu_optimizer.app", "--debug"]
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_HOST
            value: aibrix-redis-master.aibrix-system.svc.cluster.local
---
# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: aibrix-gpu-optimizer
  namespace: aibrix-system
spec:
  selector:
    app: aibrix-gpu-optimizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort