apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-optimizer
  namespace: aibrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aibrix-system
  name: gpu-optimizer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpu-optimizer
  namespace: aibrix-system
subjects:
  - kind: ServiceAccount
    name: gpu-optimizer
    namespace: aibrix-system
roleRef:
  kind: Role
  name: gpu-optimizer
  apiGroup: rbac.authorization.k8s.io