apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"models.aibricks.ai":"deepseek-coder-33b-instruct-l20","models.aibricks.com/model-name":"deepseek-coder-33b-instruct-l20"},"name":"aibricks-model-deepseek-coder-33b-instruct-l20","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"models.aibricks.ai":"deepseek-coder-33b-instruct-l20"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"models.aibricks.ai":"deepseek-coder-33b-instruct-l20"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"machine.cluster.vke.volcengine.com/gpu-name","operator":"In","values":["NVIDIA-L20"]}]}]}}},"containers":[{"command":["sleep","infinity"],"env":[{"name":"NCCL_DEBUG","value":"INFO"},{"name":"VLLM_LOGGING_LEVEL","value":"DEBUG"}],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.5.5","imagePullPolicy":"Always","name":"vllm-openai","ports":[{"containerPort":8000,"protocol":"TCP"}],"resources":{"limits":{"nvidia.com/gpu":"2"},"requests":{"nvidia.com/gpu":"2"}},"volumeMounts":[{"mountPath":"/root/.cache/huggingface","name":"cache-volume"},{"mountPath":"/models","name":"model-hostpath"},{"mountPath":"/dev/shm","name":"dshm"}]}],"volumes":[{"emptyDir":{},"name":"cache-volume"},{"hostPath":{"path":"/root/models","type":"Directory"},"name":"model-hostpath"},{"emptyDir":{"medium":"Memory","sizeLimit":"10Gi"},"name":"dshm"}]}}}}
  creationTimestamp: "2024-08-28T11:27:20Z"
  generation: 7
  labels:
    models.aibricks.ai: deepseek-coder-33b-instruct-l20
    models.aibricks.com/model-name: deepseek-coder-33b-instruct-l20
  name: aibricks-model-deepseek-coder-33b-instruct-l20
  namespace: default
  resourceVersion: "9466401"
  uid: ede9d9af-ae35-4564-a9f2-fe6eb87511ca
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      models.aibricks.ai: deepseek-coder-33b-instruct-l20
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        models.aibricks.ai: deepseek-coder-33b-instruct-l20
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-L20
      containers:
      - command:
        - sleep
        - infinity
        env:
        - name: NCCL_DEBUG
          value: INFO
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.5.5
        imagePullPolicy: Always
        name: vllm-openai
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "4"
          requests:
            nvidia.com/gpu: "4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - mountPath: /models
          name: model-hostpath
        - mountPath: /dev/shm
          name: dshm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache-volume
      - hostPath:
          path: /root/models
          type: Directory
        name: model-hostpath
      - emptyDir:
          medium: Memory
          sizeLimit: 10Gi
        name: dshm
status:
  conditions:
  - lastTransitionTime: "2024-08-28T11:27:20Z"
    lastUpdateTime: "2024-09-11T03:17:18Z"
    message: ReplicaSet "aibricks-model-deepseek-coder-33b-instruct-l20-7648958794"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-09-11T03:24:35Z"
    lastUpdateTime: "2024-09-11T03:24:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
