apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    apps.vke.volcengine.com/updated: "2025-01-15T20:29:44+08:00"
    deployment.kubernetes.io/revision: "16"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"models.aibricks.ai":"deepseek-coder-33b-instruct","models.aibricks.com/model-name":"deepseek-coder-33b-instruct"},"name":"aibricks-model-deepseek-coder-33b-instruct","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"models.aibricks.ai":"deepseek-coder-33b-instruct"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"models.aibricks.ai":"deepseek-coder-33b-instruct"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"machine.cluster.vke.volcengine.com/gpu-name","operator":"In","values":["NVIDIA-A10"]}]}]}}},"containers":[{"command":["python3","-m","vllm.entrypoints.openai.api_server","--host","0.0.0.0","--port","8000","--model","/models/deepseek-coder-33b-instruct/","--served-model-name","text2tls-sft-deepseek-coder-33b-instruct","--distributed-executor-backend","ray","--trust-remote-code","--tensor-parallel-size","4","--max-model-len","17000","--api-key","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","--enable-prefix-caching","--disable-fastapi-docs"],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.5.5-security-patch-20240919","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8000,"scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"vllm-openai","ports":[{"containerPort":8000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8000,"scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"nvidia.com/gpu":"4"},"requests":{"nvidia.com/gpu":"4"}},"volumeMounts":[{"mountPath":"/models","name":"model-hostpath"},{"mountPath":"/dev/shm","name":"dshm"}]},{"command":["gunicorn","-b",":8080","app:app","-k","uvicorn.workers.UvicornWorker"],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:latest","name":"aibrix-runtime","ports":[{"containerPort":8080,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/models","name":"model-hostpath"}]}],"initContainers":[{"command":["python","-m","aibrix.downloader","--model-uri","tos://aibrix-artifact-testing/models/text2tls-sft-deepseek-coder-33b-instruct-0909/","--local-dir","/models/"],"env":[{"name":"DOWNLOADER_MODEL_NAME","value":"deepseek-coder-33b-instruct"},{"name":"DOWNLOADER_NUM_THREADS","value":"32"},{"name":"DOWNLOADER_ALLOW_FILE_SUFFIX","value":"json, safetensors"},{"name":"TOS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"TOS_ACCESS_KEY","name":"tos-credential"}}},{"name":"TOS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"TOS_SECRET_KEY","name":"tos-credential"}}},{"name":"TOS_ENDPOINT","value":"tos-cn-beijing.ivolces.com"},{"name":"TOS_REGION","value":"cn-beijing"}],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:latest","name":"init-model","volumeMounts":[{"mountPath":"/models","name":"model-hostpath"}]}],"volumes":[{"hostPath":{"path":"/root/models","type":"DirectoryOrCreate"},"name":"model-hostpath"},{"emptyDir":{"medium":"Memory","sizeLimit":"10Gi"},"name":"dshm"}]}}}}
  creationTimestamp: "2024-09-02T11:04:01Z"
  generation: 78
  labels:
    models.aibricks.ai: deepseek-coder-33b-instruct
    models.aibricks.com/model-name: deepseek-coder-33b-instruct
  name: aibricks-model-deepseek-coder-33b-instruct
  namespace: default
  resourceVersion: "95957171"
  uid: d26c552d-7674-4e0f-b92f-42dc0a28ecf5
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      models.aibricks.ai: deepseek-coder-33b-instruct
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        models.aibricks.ai: deepseek-coder-33b-instruct
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-A10
      containers:
      - command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        - --model
        - /models/text2tls-sft-deepseek-coder-33b-instruct-0909/
        - --served-model-name
        - text2tls-sft-deepseek-coder-33b-instruct
        - --distributed-executor-backend
        - ray
        - --trust-remote-code
        - --tensor-parallel-size
        - "4"
        - --max-model-len
        - "17000"
        - --api-key
        - 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
        - --enable-prefix-caching
        - --disable-fastapi-docs
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.5.5-security-patch-20240919
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: vllm-openai
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            nvidia.com/gpu: "4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
        - mountPath: /dev/shm
          name: dshm
      - command:
        - aibrix_runtime
        - --port
        - "8080"
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.1
        imagePullPolicy: Always
        name: aibrix-runtime
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - aibrix_download
        - --model-uri
        - tos://aibrix-artifact-testing/models/text2tls-sft-deepseek-coder-33b-instruct-0909/
        - --local-dir
        - /models/
        env:
        - name: DOWNLOADER_MODEL_NAME
          value: deepseek-coder-33b-instruct
        - name: DOWNLOADER_NUM_THREADS
          value: "32"
        - name: DOWNLOADER_ALLOW_FILE_SUFFIX
          value: json, safetensors
        - name: TOS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: TOS_ACCESS_KEY
              name: tos-credential
        - name: TOS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: TOS_SECRET_KEY
              name: tos-credential
        - name: TOS_ENDPOINT
          value: tos-cn-beijing.ivolces.com
        - name: TOS_REGION
          value: cn-beijing
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.1
        imagePullPolicy: Always
        name: init-model
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /root/models
          type: DirectoryOrCreate
        name: model-hostpath
      - emptyDir:
          medium: Memory
          sizeLimit: 10Gi
        name: dshm
status:
  conditions:
  - lastTransitionTime: "2025-01-07T02:20:00Z"
    lastUpdateTime: "2025-01-07T02:20:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-07T02:18:19Z"
    lastUpdateTime: "2025-01-15T12:29:51Z"
    message: ReplicaSet "aibricks-model-deepseek-coder-33b-instruct-6f76b7f6fb" has
      successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 78
